In [1]:
import torch

In [2]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [3]:
torch.manual_seed(56)
torch.randint(0,10, (3,2)).float()

tensor([[9., 2.],
        [7., 8.],
        [4., 1.]])

In [4]:
torch.manual_seed(56)
a = torch.ones(3,3)
b = torch.randint(0,10, (3,2)).float()

In [5]:
c = a @ b

In [6]:
c

tensor([[20., 11.],
        [20., 11.],
        [20., 11.]])

In [ ]:
#now the lower triangle

In [7]:
torch.tril(torch.ones(3,3))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [8]:
torch.manual_seed(56)
a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10, (3,2)).float()
c = a @ b

In [9]:
a

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])

In [10]:
b

tensor([[9., 2.],
        [7., 8.],
        [4., 1.]])

In [11]:
c

tensor([[9.0000, 2.0000],
        [8.0000, 5.0000],
        [6.6667, 3.6667]])